"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from mongoengine import connect
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables explicitly from backend .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fahptlbc+_5y8o_2^da#895p1vq!aasxn&94tn=o363-+aurpv')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

from corsheaders.defaults import default_headers

_default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.onrender.com',
    '.railway.app',
    'critica-sigma.vercel.app',
    'critica-git-deployment-cubiangd93-1476s-projects.vercel.app',
    'critica-jch90jzha-cubiangd93-1476s-projects.vercel.app',
]
_env_allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
if _env_allowed_hosts:
    ALLOWED_HOSTS = list(dict.fromkeys(
        _default_allowed_hosts + [host.strip() for host in _env_allowed_hosts.split(',') if host.strip()]
    ))
else:
    ALLOWED_HOSTS = _default_allowed_hosts

# Default origins for development and Vercel deployments
_default_cors_origins = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://critica-sigma.vercel.app',
    'https://critica-git-deployment-cubiangd93-1476s-projects.vercel.app',
    'https://critica-jch90jzha-cubiangd93-1476s-projects.vercel.app',
]
_env_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _env_cors_origins:
    CORS_ALLOWED_ORIGINS = list(dict.fromkeys(
        _default_cors_origins + [origin.strip() for origin in _env_cors_origins.split(',') if origin.strip()]
    ))
else:
    CORS_ALLOWED_ORIGINS = _default_cors_origins

# Automatically allow all Vercel preview and production subdomains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.vercel\.app$",
]

# Allow Private Network Access (PNA) for public HTTPS Vercel frontend calling local backend
CORS_ALLOW_PRIVATE_NETWORK = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-user-email',
]

# CSRF Trusted Origins for Django 4+ (required for cross-origin POST/PUT/PATCH/DELETE)
_default_csrf_origins = [
    'https://*.vercel.app',
    'https://critica-sigma.vercel.app',
    'https://critica-git-deployment-cubiangd93-1476s-projects.vercel.app',
    'https://critica-jch90jzha-cubiangd93-1476s-projects.vercel.app',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
_env_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _env_csrf_origins:
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(
        _default_csrf_origins + [origin.strip() for origin in _env_csrf_origins.split(',') if origin.strip()]
    ))
else:
    CSRF_TRUSTED_ORIGINS = _default_csrf_origins



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',
    'api.progression',
    'api.scaffold',
    'api.lexical',
    'api.modules.logic_thread',
    'api.modules.snap_gap',
    'api.modules.tap_clues',
    'api.modules.fact_scanner',
    'api.ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # You can leave this empty
        'APP_DIRS': True, # THIS MUST BE TRUE
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database Configuration
# Primary database: MongoDB (via MongoEngine)
# SQLite for Django ORM and authentication
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MongoDB Connection
import certifi

MONGO_URI = os.getenv('MONGO_URI')
if MONGO_URI:
    connect(
        'CriticaDB',
        host=MONGO_URI,
        serverSelectionTimeoutMS=5000,
        tlsCAFile=certifi.where(),
    )
else:
    # Default to local MongoDB for development
    connect('CriticaDB', host='mongodb://localhost:27017/CriticaDB')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CustomJWTAuthentication', # Point to the file above
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# Google Gemini AI Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.5-flash')
