# Generated by Django 5.2.6 on 2026-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('node_id', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('word_id', models.CharField(blank=True, default='', max_length=100)),
                ('clue_word_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('hint_used', models.BooleanField(default=False)),
                ('hint_tier', models.IntegerField(default=0)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('inactivity_trigger', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_logs',
            },
        ),
    ]
